### ISSUE TITLE
data in binary directory and makefile problems

### ISSUE THREAD

**Issue by timsoftgit** [richard42/invasion3d#1]
Hi richard, I'm building a new (slackware) package for invasion 3d and found some issues with the makefile, and also that the data is expected to be in the binary directory, I have made some patches to the makefile, packages.cpp and packages.h which allow the dat file to be in a different directory, and also fixes the issue that the makefile doesn't install the dat file at all. 
I can email them to you if that would help.

**Comment by richard42** [comment]
Sure, you can send a pull request with the changes or email me the diffs.
